insert into COMPETITION (COMPETITION_NUMBER, COMPETITION_NAME, COMPETITION_DATE, COMPETITION_PLACE) values (1, 'PARI SUPERLEAGUE','09.05.2023','SC SOSNOVY BOR');
insert into COMPETITION (COMPETITION_NUMBER, COMPETITION_NAME, COMPETITION_DATE, COMPETITION_PLACE) values (2, 'VICTORY CUP','15.06.2023','KSK ARENA');
insert into COMPETITION (COMPETITION_NUMBER, COMPETITION_NAME, COMPETITION_DATE, COMPETITION_PLACE) values (3, 'LAVR MOTORING','16.07.2023',' AUTODROM IGOR DRIVE');

--login guest password hello
insert into "user"("login", "pass_hash") values ('guest','$2a$10$6mf3CesQx9eRGB4B3sjr8e1eSr5cYO/zt87bwYVdA4O8rmjDMDdHO');
